### PR TITLE
Added Stop Button

### PR DESCRIPTION
**Pull request by Cioraz**
Added Stop Button with it clearing the canvas. 
On Dev Branch

### CODE REVIEW

**Review by somecho — COMMENTED** [review]
After seeing your code, I added a new requirement regarding color to this issue. https://github.com/somecho/p5-cljs-web-editor/issues/1#issue-1716820885

**Comment by Cioraz** [comment]
Should i make the changes and create a new PR?

**Comment by somecho** [comment]
No, you can continue commiting to your branch and it will show up in this PR.

**Comment by somecho** [comment]
Hi the button is much too dark. Use neutral-400. See the [p5 editor](https://editor.p5js.org/) for reference on how they style their stop button.

**Comment by Cioraz** [comment]
Hey, Do you want me to also provide the rounded styling like the ps5 buttons?

**Comment by somecho** [comment]
If you are using text, just stick with the current border-radius. If you are using a glyph to represent stop, then use full border radius. The design should just be coherent.

**Review by somecho — CHANGES_REQUESTED** [review]
The button is looking nice now, but the stop logic is repeated in the code.  You can replace lines 24-27 with the new stop function that you created.

**Comment by somecho** [comment]
Great, thank you for your contribution!

**Pull request merged**
